function item_map(){
    let map = {
      "Hand Axe" : {"name": "Hand Axe", "category": "Axe", "requires": {"str": 9, "dex": 8, "int": 0, "fai": 0, "arc": 0}},
      "Jawbone Axe" : {"name": "Jawbone Axe", "category": "Axe", "requires": {"str": 14, "dex": 8, "int": 0, "fai": 0, "arc": 0}},
      "Forked Hatchet" : {"name": "Forked Hatchet", "category": "Axe", "requires": {"str": 9, "dex": 14, "int": 0, "fai": 0, "arc": 0}},
      "Iron Cleaver" : {"name": "Iron Cleaver", "category": "Axe", "requires": {"str": 15, "dex": 7, "int": 0, "fai": 0, "arc": 0}},
      "Battle Axe" : {"name": "Battle Axe", "category": "Axe", "requires": {"str": 12, "dex": 8, "int": 0, "fai": 0, "arc": 0}},
      "Ripple Blade" : {"name": "Ripple Blade", "category": "Axe", "requires": {"str": 11, "dex": 11, "int": 0, "fai": 0, "arc": 20}},
      "Icerind Hatchet" : {"name": "Icerind Hatchet", "category": "Axe", "requires": {"str": 11, "dex": 16, "int": 0, "fai": 0, "arc": 0}},
      "Sacrificial Axe" : {"name": "Sacrificial Axe", "category": "Axe", "requires": {"str": 16, "dex": 10, "int": 0, "fai": 0, "arc": 0}},
      "Celebrant's Cleaver" : {"name": "Celebrant's Cleaver", "category": "Axe", "requires": {"str": 12, "dex": 8, "int": 0, "fai": 0, "arc": 0}},
      "Rosus' Axe" : {"name": "Rosus' Axe", "category": "Axe", "requires": {"str": 18, "dex": 10, "int": 18, "fai": 0, "arc": 0}},
      "Highland Axe" : {"name": "Highland Axe", "category": "Axe", "requires": {"str": 12, "dex": 9, "int": 0, "fai": 0, "arc": 0}},
      "Warped Axe" : {"name": "Warped Axe", "category": "Axe", "requires": {"str": 24, "dex": 8, "int": 0, "fai": 0, "arc": 0}},
      "Stormhawk Axe" : {"name": "Stormhawk Axe", "category": "Axe", "requires": {"str": 19, "dex": 15, "int": 0, "fai": 0, "arc": 0}},
      "Gargoyle's Black Axe" : {"name": "Gargoyle's Black Axe", "category": "Axe", "requires": {"str": 24, "dex": 8, "int": 0, "fai": 22, "arc": 0}},
      "Hand Ballista" : {"name": "Hand Ballista", "category": "Ballista", "requires": {"str": 30, "dex": 14, "int": 0, "fai": 0, "arc": 0}},
      "Jar Cannon" : {"name": "Jar Cannon", "category": "Ballista", "requires": {"str": 34, "dex": 12, "int": 0, "fai": 0, "arc": 0}},
      "Longbow" : {"name": "Longbow", "category": "Bow", "requires": {"str": 9, "dex": 14, "int": 0, "fai": 0, "arc": 0}},
      "Albinauric Bow" : {"name": "Albinauric Bow", "category": "Bow", "requires": {"str": 7, "dex": 18, "int": 0, "fai": 0, "arc": 0}},
      "Erdtree Bow" : {"name": "Erdtree Bow", "category": "Bow", "requires": {"str": 8, "dex": 12, "int": 0, "fai": 14, "arc": 0}},
      "Horn Bow" : {"name": "Horn Bow", "category": "Bow", "requires": {"str": 10, "dex": 14, "int": 12, "fai": 0, "arc": 0}},
      "Serpent Bow" : {"name": "Serpent Bow", "category": "Bow", "requires": {"str": 8, "dex": 15, "int": 0, "fai": 0, "arc": 11}},
      "Pulley Bow" : {"name": "Pulley Bow", "category": "Bow", "requires": {"str": 11, "dex": 11, "int": 0, "fai": 0, "arc": 0}},
      "Black Bow" : {"name": "Black Bow", "category": "Bow", "requires": {"str": 9, "dex": 20, "int": 0, "fai": 0, "arc": 0}},
      "Bloodhound Claws" : {"name": "Bloodhound Claws", "category": "Claw", "requires": {"str": 10, "dex": 15, "int": 0, "fai": 0, "arc": 0}},
      "Venomous Fang" : {"name": "Venomous Fang", "category": "Claw", "requires": {"str": 9, "dex": 9, "int": 0, "fai": 0, "arc": 0}},
      "Hookclaws" : {"name": "Hookclaws", "category": "Claw", "requires": {"str": 8, "dex": 14, "int": 0, "fai": 0, "arc": 0}},
      "Raptor Talons" : {"name": "Raptor Talons", "category": "Claw", "requires": {"str": 6, "dex": 14, "int": 0, "fai": 0, "arc": 0}},
      "Watchdog's Greatsword" : {"name": "Watchdog's Greatsword", "category": "Colossal Sword", "requires": {"str": 30, "dex": 10, "int": 0, "fai": 0, "arc": 0}},
      "Greatsword" : {"name": "Greatsword", "category": "Colossal Sword", "requires": {"str": 31, "dex": 12, "int": 0, "fai": 0, "arc": 0}},
      "Troll's Golden Sword" : {"name": "Troll's Golden Sword", "category": "Colossal Sword", "requires": {"str": 29, "dex": 10, "int": 0, "fai": 0, "arc": 0}},
      "Maliketh's Black Blade" : {"name": "Maliketh's Black Blade", "category": "Colossal Sword", "requires": {"str": 34, "dex": 12, "int": 0, "fai": 20, "arc": 0}},
      "Zweihander" : {"name": "Zweihander", "category": "Colossal Sword", "requires": {"str": 19, "dex": 11, "int": 0, "fai": 0, "arc": 0}},
      "Royal Greatsword" : {"name": "Royal Greatsword", "category": "Colossal Sword", "requires": {"str": 26, "dex": 18, "int": 22, "fai": 0, "arc": 0}},
      "Godslayer's Greatsword" : {"name": "Godslayer's Greatsword", "category": "Colossal Sword", "requires": {"str": 20, "dex": 22, "int": 0, "fai": 20, "arc": 0}},
      "Grafted Blade Greatsword" : {"name": "Grafted Blade Greatsword", "category": "Colossal Sword", "requires": {"str": 40, "dex": 14, "int": 0, "fai": 0, "arc": 0}},
      "Ruins Greatsword" : {"name": "Ruins Greatsword", "category": "Colossal Sword", "requires": {"str": 50, "dex": 0, "int": 16, "fai": 0, "arc": 0}},
      "Starscourge Greatsword" : {"name": "Starscourge Greatsword", "category": "Colossal Sword", "requires": {"str": 38, "dex": 12, "int": 15, "fai": 0, "arc": 0}},
      "Troll Knight's Sword" : {"name": "Troll Knight's Sword", "category": "Colossal Sword", "requires": {"str": 20, "dex": 14, "int": 18, "fai": 0, "arc": 0}},
      "Watchdog's Staff" : {"name": "Watchdog's Staff", "category": "Colossal Weapon", "requires": {"str": 34, "dex": 10, "int": 0, "fai": 0, "arc": 0}},
      "Envoy's Greathorn" : {"name": "Envoy's Greathorn", "category": "Colossal Weapon", "requires": {"str": 28, "dex": 0, "int": 0, "fai": 0, "arc": 0}},
      "Great Club" : {"name": "Great Club", "category": "Colossal Weapon", "requires": {"str": 35, "dex": 0, "int": 0, "fai": 0, "arc": 0}},
      "Prelate's Inferno Crozier" : {"name": "Prelate's Inferno Crozier", "category": "Colossal Weapon", "requires": {"str": 45, "dex": 8, "int": 0, "fai": 0, "arc": 0}},
      "Duelist Greataxe" : {"name": "Duelist Greataxe", "category": "Colossal Weapon", "requires": {"str": 30, "dex": 10, "int": 0, "fai": 0, "arc": 0}},
      "Axe Of Godfrey" : {"name": "Axe Of Godfrey", "category": "Colossal Weapon", "requires": {"str": 42, "dex": 14, "int": 0, "fai": 0, "arc": 0}},
      "Dragon Greatclaw" : {"name": "Dragon Greatclaw", "category": "Colossal Weapon", "requires": {"str": 30, "dex": 14, "int": 0, "fai": 0, "arc": 0}},
      "Fallingstar Beast Jaw" : {"name": "Fallingstar Beast Jaw", "category": "Colossal Weapon", "requires": {"str": 34, "dex": 12, "int": 20, "fai": 0, "arc": 0}},
      "Staff Of The Avatar" : {"name": "Staff Of The Avatar", "category": "Colossal Weapon", "requires": {"str": 34, "dex": 0, "int": 0, "fai": 0, "arc": 0}},
      "Ghiza's Wheel" : {"name": "Ghiza's Wheel", "category": "Colossal Weapon", "requires": {"str": 28, "dex": 18, "int": 0, "fai": 0, "arc": 0}},
      "Giant-crusher" : {"name": "Giant-crusher", "category": "Colossal Weapon", "requires": {"str": 60, "dex": 0, "int": 0, "fai": 0, "arc": 0}},
      "Golem's Halberd" : {"name": "Golem's Halberd", "category": "Colossal Weapon", "requires": {"str": 36, "dex": 14, "int": 0, "fai": 0, "arc": 0}},
      "Troll's Hammer" : {"name": "Troll's Hammer", "category": "Colossal Weapon", "requires": {"str": 28, "dex": 8, "int": 0, "fai": 10, "arc": 0}},
      "Rotten Staff" : {"name": "Rotten Staff", "category": "Colossal Weapon", "requires": {"str": 34, "dex": 8, "int": 0, "fai": 0, "arc": 0}},
      "Rotten Greataxe" : {"name": "Rotten Greataxe", "category": "Colossal Weapon", "requires": {"str": 30, "dex": 10, "int": 0, "fai": 0, "arc": 0}},
      "Soldier's Crossbow" : {"name": "Soldier's Crossbow", "category": "Crossbow", "requires": {"str": 10, "dex": 8, "int": 0, "fai": 0, "arc": 0}},
      "Light Crossbow" : {"name": "Light Crossbow", "category": "Crossbow", "requires": {"str": 12, "dex": 8, "int": 0, "fai": 0, "arc": 0}},
      "Heavy Crossbow" : {"name": "Heavy Crossbow", "category": "Crossbow", "requires": {"str": 14, "dex": 10, "int": 0, "fai": 0, "arc": 0}},
      "Pulley Crossbow" : {"name": "Pulley Crossbow", "category": "Crossbow", "requires": {"str": 16, "dex": 16, "int": 0, "fai": 0, "arc": 0}},
      "Full Moon Crossbow" : {"name": "Full Moon Crossbow", "category": "Crossbow", "requires": {"str": 10, "dex": 10, "int": 14, "fai": 0, "arc": 0}},
      "Onyx Lord's Greatsword" : {"name": "Onyx Lord's Greatsword", "category": "Curved Greatsword", "requires": {"str": 20, "dex": 16, "int": 16, "fai": 0, "arc": 0}},
      "Crepus's Black-key Crossbow" : {"name": "Crepus's Black-key Crossbow", "category": "Crossbow", "requires": {"str": 14, "dex": 16, "int": 0, "fai": 0, "arc": 0}},
      "Arbalest" : {"name": "Arbalest", "category": "Crossbow", "requires": {"str": 18, "dex": 12, "int": 0, "fai": 0, "arc": 0}},
      "Bloodhound's Fang" : {"name": "Bloodhound's Fang", "category": "Curved Greatsword", "requires": {"str": 18, "dex": 17, "int": 0, "fai": 0, "arc": 0}},
      "Dismounter" : {"name": "Dismounter", "category": "Curved Greatsword", "requires": {"str": 19, "dex": 16, "int": 0, "fai": 0, "arc": 0}},
      "Magma Wyrm's Scalesword" : {"name": "Magma Wyrm's Scalesword", "category": "Curved Greatsword", "requires": {"str": 24, "dex": 15, "int": 0, "fai": 18, "arc": 0}},
      "Omen Cleaver" : {"name": "Omen Cleaver", "category": "Curved Greatsword", "requires": {"str": 19, "dex": 16, "int": 0, "fai": 0, "arc": 0}},
      "Zamor Curved Sword" : {"name": "Zamor Curved Sword", "category": "Curved Greatsword", "requires": {"str": 16, "dex": 18, "int": 0, "fai": 0, "arc": 0}},
      "Monk's Flameblade" : {"name": "Monk's Flameblade", "category": "Curved Greatsword", "requires": {"str": 18, "dex": 18, "int": 0, "fai": 0, "arc": 0}},
      "Beastman's Cleaver" : {"name": "Beastman's Cleaver", "category": "Curved Greatsword", "requires": {"str": 25, "dex": 14, "int": 0, "fai": 0, "arc": 0}},
      "Morgott's Cursed Sword" : {"name": "Morgott's Cursed Sword", "category": "Curved Greatsword", "requires": {"str": 14, "dex": 35, "int": 0, "fai": 0, "arc": 17}},
      "Falchion" : {"name": "Falchion", "category": "Curved Sword", "requires": {"str": 9, "dex": 13, "int": 0, "fai": 0, "arc": 0}},
      "Shamshir" : {"name": "Shamshir", "category": "Curved Sword", "requires": {"str": 7, "dex": 13, "int": 0, "fai": 0, "arc": 0}},
      "Beastman's Curved Sword" : {"name": "Beastman's Curved Sword", "category": "Curved Sword", "requires": {"str": 13, "dex": 11, "int": 0, "fai": 0, "arc": 0}},
      "Shotel" : {"name": "Shotel", "category": "Curved Sword", "requires": {"str": 9, "dex": 19, "int": 0, "fai": 0, "arc": 0}},
      "Magma Blade" : {"name": "Magma Blade", "category": "Curved Sword", "requires": {"str": 9, "dex": 15, "int": 0, "fai": 16, "arc": 0}},
      "Flowing Curved Sword" : {"name": "Flowing Curved Sword", "category": "Curved Sword", "requires": {"str": 9, "dex": 17, "int": 0, "fai": 0, "arc": 0}},
      "Wing Of Astel" : {"name": "Wing Of Astel", "category": "Curved Sword", "requires": {"str": 7, "dex": 17, "int": 20, "fai": 0, "arc": 0}},
      "Eclipse Shotel" : {"name": "Eclipse Shotel", "category": "Curved Sword", "requires": {"str": 10, "dex": 25, "int": 0, "fai": 30, "arc": 0}},
      "Serpent-god's Curved Sword" : {"name": "Serpent-god's Curved Sword", "category": "Curved Sword", "requires": {"str": 13, "dex": 9, "int": 0, "fai": 0, "arc": 0}},
      "Scavenger's Curved Sword" : {"name": "Scavenger's Curved Sword", "category": "Curved Sword", "requires": {"str": 9, "dex": 14, "int": 0, "fai": 0, "arc": 0}},
      "Mantis Blade" : {"name": "Mantis Blade", "category": "Curved Sword", "requires": {"str": 10, "dex": 12, "int": 0, "fai": 0, "arc": 0}},
      "Scimitar" : {"name": "Scimitar", "category": "Curved Sword", "requires": {"str": 7, "dex": 13, "int": 0, "fai": 0, "arc": 0}},
      "Nox Flowing Sword" : {"name": "Nox Flowing Sword", "category": "Curved Sword", "requires": {"str": 8, "dex": 15, "int": 0, "fai": 0, "arc": 0}},
      "Dagger" : {"name": "Dagger", "category": "Dagger", "requires": {"str": 5, "dex": 9, "int": 0, "fai": 0, "arc": 0}},
      "Grossmesser" : {"name": "Grossmesser", "category": "Curved Sword", "requires": {"str": 14, "dex": 12, "int": 0, "fai": 0, "arc": 0}},
      "Black Knife" : {"name": "Black Knife", "category": "Dagger", "requires": {"str": 8, "dex": 12, "int": 0, "fai": 18, "arc": 0}},
      "Parrying Dagger" : {"name": "Parrying Dagger", "category": "Dagger", "requires": {"str": 5, "dex": 14, "int": 0, "fai": 0, "arc": 0}},
      "Miséricorde" : {"name": "Miséricorde", "category": "Dagger", "requires": {"str": 7, "dex": 12, "int": 0, "fai": 0, "arc": 0}},
      "Reduvia" : {"name": "Reduvia", "category": "Dagger", "requires": {"str": 5, "dex": 13, "int": 0, "fai": 0, "arc": 13}},
      "Crystal Knife" : {"name": "Crystal Knife", "category": "Dagger", "requires": {"str": 8, "dex": 12, "int": 9, "fai": 0, "arc": 0}},
      "Celebrant's Sickle" : {"name": "Celebrant's Sickle", "category": "Dagger", "requires": {"str": 6, "dex": 11, "int": 0, "fai": 0, "arc": 0}},
      "Glintstone Kris" : {"name": "Glintstone Kris", "category": "Dagger", "requires": {"str": 5, "dex": 12, "int": 16, "fai": 0, "arc": 0}},
      "Scorpion's Stinger" : {"name": "Scorpion's Stinger", "category": "Dagger", "requires": {"str": 6, "dex": 12, "int": 0, "fai": 0, "arc": 0}},
      "Great Knife" : {"name": "Great Knife", "category": "Dagger", "requires": {"str": 6, "dex": 12, "int": 0, "fai": 0, "arc": 0}},
      "Wakizashi" : {"name": "Wakizashi", "category": "Dagger", "requires": {"str": 9, "dex": 13, "int": 0, "fai": 0, "arc": 0}},
      "Cinquedea" : {"name": "Cinquedea", "category": "Dagger", "requires": {"str": 10, "dex": 10, "int": 0, "fai": 0, "arc": 0}},
      "Ivory Sickle" : {"name": "Ivory Sickle", "category": "Dagger", "requires": {"str": 6, "dex": 11, "int": 13, "fai": 0, "arc": 0}},
      "Erdsteel Dagger" : {"name": "Erdsteel Dagger", "category": "Dagger", "requires": {"str": 7, "dex": 12, "int": 0, "fai": 14, "arc": 0}},
      "Blade Of Calling" : {"name": "Blade Of Calling", "category": "Dagger", "requires": {"str": 6, "dex": 13, "int": 0, "fai": 15, "arc": 0}},
      "Bloodstained Dagger" : {"name": "Bloodstained Dagger", "category": "Dagger", "requires": {"str": 9, "dex": 12, "int": 0, "fai": 0, "arc": 0}},
      "Spiked Caestus" : {"name": "Spiked Caestus", "category": "Fist", "requires": {"str": 8, "dex": 10, "int": 0, "fai": 0, "arc": 0}},
      "Caestus" : {"name": "Caestus", "category": "Fist", "requires": {"str": 8, "dex": 8, "int": 0, "fai": 0, "arc": 0}},
      "Grafted Dragon" : {"name": "Grafted Dragon", "category": "Fist", "requires": {"str": 20, "dex": 14, "int": 0, "fai": 16, "arc": 0}},
      "Iron Ball" : {"name": "Iron Ball", "category": "Fist", "requires": {"str": 11, "dex": 8, "int": 0, "fai": 0, "arc": 0}},
      "Star Fist" : {"name": "Star Fist", "category": "Fist", "requires": {"str": 12, "dex": 8, "int": 0, "fai": 0, "arc": 0}},
      "Katar" : {"name": "Katar", "category": "Fist", "requires": {"str": 8, "dex": 10, "int": 0, "fai": 0, "arc": 0}},
      "Clinging Bone" : {"name": "Clinging Bone", "category": "Fist", "requires": {"str": 8, "dex": 22, "int": 0, "fai": 0, "arc": 16}},
      "Cipher Pata" : {"name": "Cipher Pata", "category": "Fist", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 30, "arc": 0}},
      "Veteran's Prosthesis" : {"name": "Veteran's Prosthesis", "category": "Fist", "requires": {"str": 15, "dex": 12, "int": 0, "fai": 0, "arc": 0}},
      "Nightrider Flail" : {"name": "Nightrider Flail", "category": "Flail", "requires": {"str": 10, "dex": 24, "int": 0, "fai": 0, "arc": 0}},
      "Flail" : {"name": "Flail", "category": "Flail", "requires": {"str": 10, "dex": 18, "int": 0, "fai": 0, "arc": 0}},
      "Family Heads" : {"name": "Family Heads", "category": "Flail", "requires": {"str": 8, "dex": 18, "int": 16, "fai": 0, "arc": 0}},
      "Bastard's Stars" : {"name": "Bastard's Stars", "category": "Flail", "requires": {"str": 8, "dex": 22, "int": 22, "fai": 0, "arc": 0}},
      "Glintstone Staff" : {"name": "Glintstone Staff", "category": "Glintstone Staff", "requires": {"str": 6, "dex": 0, "int": 10, "fai": 0, "arc": 0}},
      "Crystal Staff" : {"name": "Crystal Staff", "category": "Glintstone Staff", "requires": {"str": 8, "dex": 0, "int": 48, "fai": 0, "arc": 0}},
      "Chainlink Flail" : {"name": "Chainlink Flail", "category": "Flail", "requires": {"str": 18, "dex": 12, "int": 0, "fai": 0, "arc": 0}},
      "Gelmir Glintstone Staff" : {"name": "Gelmir Glintstone Staff", "category": "Glintstone Staff", "requires": {"str": 6, "dex": 0, "int": 14, "fai": 14, "arc": 0}},
      "Demi-human Queen's Staff" : {"name": "Demi-human Queen's Staff", "category": "Glintstone Staff", "requires": {"str": 6, "dex": 0, "int": 10, "fai": 0, "arc": 0}},
      "Carian Regal Scepter" : {"name": "Carian Regal Scepter", "category": "Glintstone Staff", "requires": {"str": 8, "dex": 10, "int": 60, "fai": 0, "arc": 0}},
      "Astrologer's Staff" : {"name": "Astrologer's Staff", "category": "Glintstone Staff", "requires": {"str": 7, "dex": 0, "int": 16, "fai": 0, "arc": 0}},
      "Digger's Staff" : {"name": "Digger's Staff", "category": "Glintstone Staff", "requires": {"str": 8, "dex": 0, "int": 12, "fai": 0, "arc": 0}},
      "Prince Of Death's Star" : {"name": "Prince Of Death's Star", "category": "Glintstone Staff", "requires": {"str": 6, "dex": 0, "int": 18, "fai": 18, "arc": 0}},
      "Carian Glintblade Staff" : {"name": "Carian Glintblade Staff", "category": "Glintstone Staff", "requires": {"str": 6, "dex": 12, "int": 22, "fai": 0, "arc": 0}},
      "Albinauric Staff" : {"name": "Albinauric Staff", "category": "Glintstone Staff", "requires": {"str": 6, "dex": 0, "int": 10, "fai": 0, "arc": 12}},
      "Academy Glintstone Staff" : {"name": "Academy Glintstone Staff", "category": "Glintstone Staff", "requires": {"str": 6, "dex": 0, "int": 28, "fai": 0, "arc": 0}},
      "Carian Glintstone Staff" : {"name": "Carian Glintstone Staff", "category": "Glintstone Staff", "requires": {"str": 6, "dex": 8, "int": 24, "fai": 0, "arc": 0}},
      "Azur's Glintstone Staff" : {"name": "Azur's Glintstone Staff", "category": "Glintstone Staff", "requires": {"str": 10, "dex": 0, "int": 52, "fai": 0, "arc": 0}},
      "Lusat's Glintstone Staff" : {"name": "Lusat's Glintstone Staff", "category": "Glintstone Staff", "requires": {"str": 10, "dex": 0, "int": 52, "fai": 0, "arc": 0}},
      "Meteorite Staff" : {"name": "Meteorite Staff", "category": "Glintstone Staff", "requires": {"str": 6, "dex": 0, "int": 18, "fai": 0, "arc": 0}},
      "Staff Of The Guilty" : {"name": "Staff Of The Guilty", "category": "Glintstone Staff", "requires": {"str": 8, "dex": 0, "int": 0, "fai": 12, "arc": 0}},
      "Rotten Crystal Staff" : {"name": "Rotten Crystal Staff", "category": "Glintstone Staff", "requires": {"str": 8, "dex": 0, "int": 48, "fai": 0, "arc": 0}},
      "Greataxe" : {"name": "Greataxe", "category": "Greataxe", "requires": {"str": 30, "dex": 8, "int": 0, "fai": 0, "arc": 0}},
      "Great Omenkiller Cleaver" : {"name": "Great Omenkiller Cleaver", "category": "Greataxe", "requires": {"str": 23, "dex": 12, "int": 0, "fai": 0, "arc": 0}},
      "Staff Of Loss" : {"name": "Staff Of Loss", "category": "Glintstone Staff", "requires": {"str": 6, "dex": 12, "int": 14, "fai": 0, "arc": 0}},
      "Crescent Moon Axe" : {"name": "Crescent Moon Axe", "category": "Greataxe", "requires": {"str": 25, "dex": 15, "int": 0, "fai": 0, "arc": 0}},
      "Axe Of Godrick" : {"name": "Axe Of Godrick", "category": "Greataxe", "requires": {"str": 34, "dex": 22, "int": 0, "fai": 0, "arc": 0}},
      "Longhaft Axe" : {"name": "Longhaft Axe", "category": "Greataxe", "requires": {"str": 24, "dex": 8, "int": 0, "fai": 0, "arc": 0}},
      "Executioner's Greataxe" : {"name": "Executioner's Greataxe", "category": "Greataxe", "requires": {"str": 34, "dex": 8, "int": 0, "fai": 0, "arc": 0}},
      "Rusted Anchor" : {"name": "Rusted Anchor", "category": "Greataxe", "requires": {"str": 26, "dex": 9, "int": 0, "fai": 0, "arc": 0}},
      "Winged Greathorn" : {"name": "Winged Greathorn", "category": "Greataxe", "requires": {"str": 30, "dex": 20, "int": 0, "fai": 0, "arc": 0}},
      "Butchering Knife" : {"name": "Butchering Knife", "category": "Greataxe", "requires": {"str": 16, "dex": 20, "int": 0, "fai": 0, "arc": 0}},
      "Gargoyle's Great Axe" : {"name": "Gargoyle's Great Axe", "category": "Greataxe", "requires": {"str": 24, "dex": 8, "int": 0, "fai": 0, "arc": 0}},
      "Lion Greatbow" : {"name": "Lion Greatbow", "category": "Greatbow", "requires": {"str": 22, "dex": 18, "int": 0, "fai": 0, "arc": 0}},
      "Erdtree Greatbow" : {"name": "Erdtree Greatbow", "category": "Greatbow", "requires": {"str": 20, "dex": 14, "int": 0, "fai": 14, "arc": 0}},
      "Golem Greatbow" : {"name": "Golem Greatbow", "category": "Greatbow", "requires": {"str": 24, "dex": 18, "int": 0, "fai": 0, "arc": 0}},
      "Greatbow" : {"name": "Greatbow", "category": "Greatbow", "requires": {"str": 20, "dex": 20, "int": 0, "fai": 0, "arc": 0}},
      "Mohgwyn's Sacred Spear" : {"name": "Mohgwyn's Sacred Spear", "category": "Great Spear", "requires": {"str": 24, "dex": 14, "int": 0, "fai": 0, "arc": 27}},
      "Siluria's Tree" : {"name": "Siluria's Tree", "category": "Great Spear", "requires": {"str": 27, "dex": 13, "int": 0, "fai": 0, "arc": 0, "": 20}},
      "Vyke's War Spear" : {"name": "Vyke's War Spear", "category": "Great Spear", "requires": {"str": 16, "dex": 20, "int": 0, "fai": 18, "arc": 0}},
      "Serpent-hunter" : {"name": "Serpent-hunter", "category": "Great Spear", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 0, "arc": 0, "-": 0}},
      "Lance" : {"name": "Lance", "category": "Great Spear", "requires": {"str": 20, "dex": 14, "int": 0, "fai": 0, "arc": 0}},
      "Treespear" : {"name": "Treespear", "category": "Great Spear", "requires": {"str": 15, "dex": 22, "int": 0, "fai": 0, "arc": 0, "": 18}},
      "Bastard Sword" : {"name": "Bastard Sword", "category": "Greatsword", "requires": {"str": 16, "dex": 10, "int": 0, "fai": 0, "arc": 0}},
      "Forked Greatsword" : {"name": "Forked Greatsword", "category": "Greatsword", "requires": {"str": 14, "dex": 16, "int": 0, "fai": 0, "arc": 0}},
      "Iron Greatsword" : {"name": "Iron Greatsword", "category": "Greatsword", "requires": {"str": 18, "dex": 10, "int": 0, "fai": 0, "arc": 0}},
      "Lordsworn's Greatsword" : {"name": "Lordsworn's Greatsword", "category": "Greatsword", "requires": {"str": 16, "dex": 10, "int": 0, "fai": 0, "arc": 0}},
      "Knight's Greatsword" : {"name": "Knight's Greatsword", "category": "Greatsword", "requires": {"str": 16, "dex": 12, "int": 0, "fai": 0, "arc": 0}},
      "Flamberge" : {"name": "Flamberge", "category": "Greatsword", "requires": {"str": 15, "dex": 14, "int": 0, "fai": 0, "arc": 0}},
      "Ordovis's Greatsword" : {"name": "Ordovis's Greatsword", "category": "Greatsword", "requires": {"str": 25, "dex": 13, "int": 0, "fai": 15, "arc": 0}},
      "Alabaster Lord's Sword" : {"name": "Alabaster Lord's Sword", "category": "Greatsword", "requires": {"str": 16, "dex": 12, "int": 18, "fai": 0, "arc": 0}},
      "Banished Knight's Greatsword" : {"name": "Banished Knight's Greatsword", "category": "Greatsword", "requires": {"str": 17, "dex": 0, "int": 0, "fai": 0, "arc": 0}},
      "Dark Moon Greatsword" : {"name": "Dark Moon Greatsword", "category": "Greatsword", "requires": {"str": 16, "dex": 11, "int": 38, "fai": 0, "arc": 0}},
      "Sacred Relic Sword" : {"name": "Sacred Relic Sword", "category": "Greatsword", "requires": {"str": 14, "dex": 24, "int": 0, "fai": 22, "arc": 0}},
      "Helphen's Steeple" : {"name": "Helphen's Steeple", "category": "Greatsword", "requires": {"str": 19, "dex": 10, "int": 22, "fai": 0, "arc": 0}},
      "Blasphemous Blade" : {"name": "Blasphemous Blade", "category": "Greatsword", "requires": {"str": 22, "dex": 15, "int": 0, "fai": 21, "arc": 0}},
      "Marais Executioner's Sword" : {"name": "Marais Executioner's Sword", "category": "Greatsword", "requires": {"str": 24, "dex": 14, "int": 0, "fai": 0, "arc": 23}},
      "Sword Of Milos" : {"name": "Sword Of Milos", "category": "Greatsword", "requires": {"str": 15, "dex": 19, "int": 0, "fai": 0, "arc": 0}},
      "Golden Order Greatsword" : {"name": "Golden Order Greatsword", "category": "Greatsword", "requires": {"str": 16, "dex": 21, "int": 0, "fai": 18, "arc": 0}},
      "Claymore" : {"name": "Claymore", "category": "Greatsword", "requires": {"str": 16, "dex": 13, "int": 0, "fai": 0, "arc": 0}},
      "Gargoyle's Greatsword" : {"name": "Gargoyle's Greatsword", "category": "Greatsword", "requires": {"str": 18, "dex": 10, "int": 0, "fai": 0, "arc": 0}},
      "Death's Poker" : {"name": "Death's Poker", "category": "Greatsword", "requires": {"str": 15, "dex": 17, "int": 11, "fai": 0, "arc": 0}},
      "Gargoyle's Blackblade" : {"name": "Gargoyle's Blackblade", "category": "Greatsword", "requires": {"str": 18, "dex": 10, "int": 0, "fai": 22, "arc": 0}},
      "Pest's Glaive" : {"name": "Pest's Glaive", "category": "Halberd", "requires": {"str": 13, "dex": 13, "int": 0, "fai": 0, "arc": 0}},
      "Halberd" : {"name": "Halberd", "category": "Halberd", "requires": {"str": 14, "dex": 12, "int": 0, "fai": 0, "arc": 0}},
      "Lucerne" : {"name": "Lucerne", "category": "Halberd", "requires": {"str": 15, "dex": 12, "int": 0, "fai": 0, "arc": 0}},
      "Banished Knight's Halberd" : {"name": "Banished Knight's Halberd", "category": "Halberd", "requires": {"str": 14, "dex": 12, "int": 0, "fai": 0, "arc": 0}},
      "Commander's Standard" : {"name": "Commander's Standard", "category": "Halberd", "requires": {"str": 24, "dex": 14, "int": 0, "fai": 0, "arc": 0}},
      "Ripple Crescent Halberd" : {"name": "Ripple Crescent Halberd", "category": "Halberd", "requires": {"str": 12, "dex": 0, "int": 0, "fai": 0, "arc": 0}},
      "Nightrider Glaive" : {"name": "Nightrider Glaive", "category": "Halberd", "requires": {"str": 26, "dex": 10, "int": 0, "fai": 0, "arc": 0}},
      "Vulgar Militia Saw" : {"name": "Vulgar Militia Saw", "category": "Halberd", "requires": {"str": 15, "dex": 0, "int": 0, "fai": 0, "arc": 0}},
      "Golden Halberd" : {"name": "Golden Halberd", "category": "Halberd", "requires": {"str": 30, "dex": 14, "int": 0, "fai": 12, "arc": 0}},
      "Glaive" : {"name": "Glaive", "category": "Halberd", "requires": {"str": 18, "dex": 15, "int": 0, "fai": 0, "arc": 0}},
      "Loretta's War Sickle" : {"name": "Loretta's War Sickle", "category": "Halberd", "requires": {"str": 20, "dex": 15, "int": 20, "fai": 0, "arc": 0}},
      "Guardian's Swordspear" : {"name": "Guardian's Swordspear", "category": "Halberd", "requires": {"str": 17, "dex": 16, "int": 0, "fai": 0, "arc": 0}},
      "Dragon Halberd" : {"name": "Dragon Halberd", "category": "Halberd", "requires": {"str": 22, "dex": 10, "int": 0, "fai": 0, "arc": 0}},
      "Vulgar Militia Shotel" : {"name": "Vulgar Militia Shotel", "category": "Curved Sword", "requires": {"str": 14, "dex": 16, "int": 0, "fai": 0, "arc": 0}},
      "Gargoyle's Halberd" : {"name": "Gargoyle's Halberd", "category": "Halberd", "requires": {"str": 26, "dex": 10, "int": 0, "fai": 0, "arc": 0}},
      "Mace" : {"name": "Mace", "category": "Hammer", "requires": {"str": 12, "dex": 7, "int": 0, "fai": 0, "arc": 0}},
      "Gargoyle's Black Halberd" : {"name": "Gargoyle's Black Halberd", "category": "Halberd", "requires": {"str": 26, "dex": 10, "int": 0, "fai": 22, "arc": 0}},
      "Curved Club" : {"name": "Curved Club", "category": "Hammer", "requires": {"str": 11, "dex": 7, "int": 0, "fai": 0, "arc": 0}},
      "Warpick" : {"name": "Warpick", "category": "Hammer", "requires": {"str": 11, "dex": 9, "int": 0, "fai": 0, "arc": 0}},
      "Club" : {"name": "Club", "category": "Hammer", "requires": {"str": 10, "dex": 0, "int": 0, "fai": 0, "arc": 0}},
      "Spiked Club" : {"name": "Spiked Club", "category": "Hammer", "requires": {"str": 12, "dex": 7, "int": 0, "fai": 0, "arc": 0}},
      "Hammer" : {"name": "Hammer", "category": "Hammer", "requires": {"str": 14, "dex": 7, "int": 0, "fai": 0, "arc": 0}},
      "Varré's Bouquet" : {"name": "Varré's Bouquet", "category": "Hammer", "requires": {"str": 8, "dex": 16, "int": 0, "fai": 0, "arc": 24}},
      "Morning Star" : {"name": "Morning Star", "category": "Hammer", "requires": {"str": 12, "dex": 8, "int": 0, "fai": 0, "arc": 0}},
      "Monk's Flamemace" : {"name": "Monk's Flamemace", "category": "Hammer", "requires": {"str": 13, "dex": 13, "int": 0, "fai": 0, "arc": 0}},
      "Envoy's Horn" : {"name": "Envoy's Horn", "category": "Hammer", "requires": {"str": 10, "dex": 0, "int": 0, "fai": 0, "arc": 0}},
      "Scepter Of The All-knowing" : {"name": "Scepter Of The All-knowing", "category": "Hammer", "requires": {"str": 12, "dex": 18, "int": 21, "fai": 0, "arc": 0}},
      "Nox Flowing Hammer" : {"name": "Nox Flowing Hammer", "category": "Hammer", "requires": {"str": 17, "dex": 7, "int": 0, "fai": 0, "arc": 0}},
      "Ringed Finger" : {"name": "Ringed Finger", "category": "Hammer", "requires": {"str": 17, "dex": 7, "int": 0, "fai": 0, "arc": 0}},
      "Stone Club" : {"name": "Stone Club", "category": "Hammer", "requires": {"str": 16, "dex": 8, "int": 0, "fai": 0, "arc": 0}},
      "Marika's Hammer" : {"name": "Marika's Hammer", "category": "Hammer", "requires": {"str": 20, "dex": 0, "int": 0, "fai": 0, "arc": 0}},
      "Bloody Helice" : {"name": "Bloody Helice", "category": "Heavy Thrusting Sword", "requires": {"str": 16, "dex": 19, "int": 0, "fai": 0, "arc": 17}},
      "Great Épée" : {"name": "Great Épée", "category": "Heavy Thrusting Sword", "requires": {"str": 15, "dex": 16, "int": 0, "fai": 0, "arc": 0}},
      "Godskin Stitcher" : {"name": "Godskin Stitcher", "category": "Heavy Thrusting Sword", "requires": {"str": 14, "dex": 17, "int": 0, "fai": 0, "arc": 0}},
      "Dragon King's Cragblade" : {"name": "Dragon King's Cragblade", "category": "Heavy Thrusting Sword", "requires": {"str": 18, "dex": 37, "int": 0, "fai": 0, "arc": 0}},
      "Uchigatana" : {"name": "Uchigatana", "category": "Katana", "requires": {"str": 11, "dex": 15, "int": 0, "fai": 0, "arc": 0}},
      "Nagakiba" : {"name": "Nagakiba", "category": "Katana", "requires": {"str": 18, "dex": 22, "int": 0, "fai": 0, "arc": 0}},
      "Hand Of Malenia" : {"name": "Hand Of Malenia", "category": "Katana", "requires": {"str": 16, "dex": 48, "int": 0, "fai": 0, "arc": 0}},
      "Meteoric Ore Blade" : {"name": "Meteoric Ore Blade", "category": "Katana", "requires": {"str": 15, "dex": 14, "int": 18, "fai": 0, "arc": 0}},
      "Rivers Of Blood" : {"name": "Rivers Of Blood", "category": "Katana", "requires": {"str": 12, "dex": 18, "int": 0, "fai": 0, "arc": 20}},
      "Moonveil" : {"name": "Moonveil", "category": "Katana", "requires": {"str": 12, "dex": 18, "int": 23, "fai": 0, "arc": 0}},
      "Dragonscale Blade" : {"name": "Dragonscale Blade", "category": "Katana", "requires": {"str": 12, "dex": 20, "int": 0, "fai": 0, "arc": 0}},
      "Serpentbone Blade" : {"name": "Serpentbone Blade", "category": "Katana", "requires": {"str": 11, "dex": 22, "int": 0, "fai": 0, "arc": 0}},
      "Shortbow" : {"name": "Shortbow", "category": "Light Bow", "requires": {"str": 8, "dex": 10, "int": 0, "fai": 0, "arc": 0}},
      "Misbegotten Shortbow" : {"name": "Misbegotten Shortbow", "category": "Light Bow", "requires": {"str": 16, "dex": 8, "int": 0, "fai": 0, "arc": 0}},
      "Red Branch Shortbow" : {"name": "Red Branch Shortbow", "category": "Light Bow", "requires": {"str": 8, "dex": 16, "int": 0, "fai": 0, "arc": 0}},
      "Harp Bow" : {"name": "Harp Bow", "category": "Light Bow", "requires": {"str": 9, "dex": 9, "int": 0, "fai": 0, "arc": 0}},
      "Composite Bow" : {"name": "Composite Bow", "category": "Light Bow", "requires": {"str": 15, "dex": 15, "int": 0, "fai": 0, "arc": 0}},
      "Scythe" : {"name": "Scythe", "category": "Reaper", "requires": {"str": 14, "dex": 14, "int": 0, "fai": 0, "arc": 0}},
      "Grave Scythe" : {"name": "Grave Scythe", "category": "Reaper", "requires": {"str": 17, "dex": 0, "int": 0, "fai": 0, "arc": 0}},
      "Halo Scythe" : {"name": "Halo Scythe", "category": "Reaper", "requires": {"str": 13, "dex": 16, "int": 0, "fai": 15, "arc": 0}},
      "Winged Scythe" : {"name": "Winged Scythe", "category": "Reaper", "requires": {"str": 16, "dex": 16, "int": 0, "fai": 24, "arc": 0}},
      "Finger Seal" : {"name": "Finger Seal", "category": "Sacred Seal", "requires": {"str": 4, "dex": 0, "int": 0, "fai": 10, "arc": 0}},
      "Godslayer's Seal" : {"name": "Godslayer's Seal", "category": "Sacred Seal", "requires": {"str": 4, "dex": 0, "int": 0, "fai": 27, "arc": 0}},
      "Giant's Seal" : {"name": "Giant's Seal", "category": "Sacred Seal", "requires": {"str": 4, "dex": 0, "int": 0, "fai": 14, "arc": 0}},
      "Clawmark Seal" : {"name": "Clawmark Seal", "category": "Sacred Seal", "requires": {"str": 4, "dex": 0, "int": 0, "fai": 10, "arc": 0}},
      "Golden Order Seal" : {"name": "Golden Order Seal", "category": "Sacred Seal", "requires": {"str": 0, "dex": 0, "int": 17, "fai": 17, "arc": 0}},
      "Erdtree Seal" : {"name": "Erdtree Seal", "category": "Sacred Seal", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 40, "arc": 0}},
      "Erdtree Seal" : {"name": "Erdtree Seal", "category": "Sacred Seal", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 40, "arc": 0}},
      "Dragon Communion Seal" : {"name": "Dragon Communion Seal", "category": "Sacred Seal", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 10, "arc": 10}},
      "Frenzied Flame Seal" : {"name": "Frenzied Flame Seal", "category": "Sacred Seal", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 10, "arc": 10}},
      "Spear" : {"name": "Spear", "category": "Spear", "requires": {"str": 12, "dex": 15, "int": 0, "fai": 0, "arc": 0}},
      "Short Spear" : {"name": "Short Spear", "category": "Spear", "requires": {"str": 10, "dex": 10, "int": 0, "fai": 0, "arc": 0}},
      "Crystal Spear" : {"name": "Crystal Spear", "category": "Spear", "requires": {"str": 10, "dex": 16, "int": 16, "fai": 0, "arc": 0}},
      "Clayman's Harpoon" : {"name": "Clayman's Harpoon", "category": "Spear", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 0, "arc": 0}},
      "Partisan" : {"name": "Partisan", "category": "Spear", "requires": {"str": 15, "dex": 12, "int": 0, "fai": 0, "arc": 0}},
      "Celebrant's Rib-rake" : {"name": "Celebrant's Rib-rake", "category": "Spear", "requires": {"str": 8, "dex": 14, "int": 0, "fai": 0, "arc": 0}},
      "Cleanrot Spear" : {"name": "Cleanrot Spear", "category": "Spear", "requires": {"str": 16, "dex": 0, "int": 0, "fai": 0, "arc": 0}},
      "Pike" : {"name": "Pike", "category": "Spear", "requires": {"str": 20, "dex": 14, "int": 0, "fai": 0, "arc": 0}},
      "Torchpole" : {"name": "Torchpole", "category": "Spear", "requires": {"str": 14, "dex": 15, "int": 0, "fai": 0, "arc": 0}},
      "Bolt Of Gransax" : {"name": "Bolt Of Gransax", "category": "Spear", "requires": {"str": 20, "dex": 40, "int": 0, "fai": 0, "arc": 0}},
      "Cross-naginata" : {"name": "Cross-naginata", "category": "Spear", "requires": {"str": 16, "dex": 20, "int": 0, "fai": 0, "arc": 0}},
      "Death Ritual Spear" : {"name": "Death Ritual Spear", "category": "Spear", "requires": {"str": 11, "dex": 20, "int": 18, "fai": 0, "arc": 0}},
      "Inquisitor's Girandole" : {"name": "Inquisitor's Girandole", "category": "Spear", "requires": {"str": 18, "dex": 15, "int": 0, "fai": 16, "arc": 0}},
      "Spiked Spear" : {"name": "Spiked Spear", "category": "Spear", "requires": {"str": 14, "dex": 0, "int": 0, "fai": 0, "arc": 0}},
      "Rotten Crystal Spear" : {"name": "Rotten Crystal Spear", "category": "Spear", "requires": {"str": 10, "dex": 16, "int": 16, "fai": 0, "arc": 0}},
      "Iron Spear" : {"name": "Iron Spear", "category": "Spear", "requires": {"str": 13, "dex": 11, "int": 0, "fai": 0, "arc": 0}},
      "Winged Spear" : {"name": "Winged Spear", "category": "Spear", "requires": {"str": 10, "dex": 10, "int": 0, "fai": 0, "arc": 0}},
      "Longsword" : {"name": "Longsword", "category": "Straight Sword", "requires": {"str": 10, "dex": 10, "int": 0, "fai": 0, "arc": 0}},
      "Short Sword" : {"name": "Short Sword", "category": "Straight Sword", "requires": {"str": 8, "dex": 10, "int": 0, "fai": 0, "arc": 0}},
      "Broadsword" : {"name": "Broadsword", "category": "Straight Sword", "requires": {"str": 10, "dex": 10, "int": 0, "fai": 0, "arc": 0}},
      "Lordsworn's Straight Sword" : {"name": "Lordsworn's Straight Sword", "category": "Straight Sword", "requires": {"str": 10, "dex": 10, "int": 0, "fai": 0, "arc": 0}},
      "Weathered Straight Sword" : {"name": "Weathered Straight Sword", "category": "Straight Sword", "requires": {"str": 7, "dex": 10, "int": 0, "fai": 0, "arc": 0}},
      "Golden Epitaph" : {"name": "Golden Epitaph", "category": "Straight Sword", "requires": {"str": 12, "dex": 10, "int": 0, "fai": 14, "arc": 0}},
      "Ornamental Straight Sword" : {"name": "Ornamental Straight Sword", "category": "Straight Sword", "requires": {"str": 10, "dex": 14, "int": 0, "fai": 0, "arc": 0}},
      "Coded Sword" : {"name": "Coded Sword", "category": "Straight Sword", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 20, "arc": 0}},
      "Sword Of Night And Flame" : {"name": "Sword Of Night And Flame", "category": "Straight Sword", "requires": {"str": 12, "dex": 12, "int": 0, "fai": 24, "arc": 0, "": 24}},
      "Carian Knight's Sword" : {"name": "Carian Knight's Sword", "category": "Straight Sword", "requires": {"str": 10, "dex": 10, "int": 18, "fai": 0, "arc": 0}},
      "Crystal Sword" : {"name": "Crystal Sword", "category": "Straight Sword", "requires": {"str": 13, "dex": 10, "int": 15, "fai": 0, "arc": 0}},
      "Sword Of St Trina" : {"name": "Sword Of St Trina", "category": "Straight Sword", "requires": {"str": 10, "dex": 12, "int": 0, "fai": 0, "arc": 0, "": 14}},
      "Miquellan Knight's Sword" : {"name": "Miquellan Knight's Sword", "category": "Straight Sword", "requires": {"str": 11, "dex": 11, "int": 0, "fai": 16, "arc": 0}},
      "Cane Sword" : {"name": "Cane Sword", "category": "Straight Sword", "requires": {"str": 8, "dex": 11, "int": 0, "fai": 0, "arc": 0}},
      "Regalia Of Eochaid" : {"name": "Regalia Of Eochaid", "category": "Straight Sword", "requires": {"str": 12, "dex": 0, "int": 0, "fai": 0, "arc": 0}},
      "Noble's Slender Sword" : {"name": "Noble's Slender Sword", "category": "Straight Sword", "requires": {"str": 8, "dex": 0, "int": 0, "fai": 0, "arc": 0}},
      "Warhawk's Talon" : {"name": "Warhawk's Talon", "category": "Straight Sword", "requires": {"str": 10, "dex": 16, "int": 0, "fai": 0, "arc": 0}},
      "Rotten Crystal Sword" : {"name": "Rotten Crystal Sword", "category": "Straight Sword", "requires": {"str": 13, "dex": 10, "int": 15, "fai": 0, "arc": 0}},
      "Lazuli Glintstone Sword" : {"name": "Lazuli Glintstone Sword", "category": "Straight Sword", "requires": {"str": 8, "dex": 0, "int": 0, "fai": 0, "arc": 0}},
      "Estoc" : {"name": "Estoc", "category": "Thrusting Sword", "requires": {"str": 11, "dex": 13, "int": 0, "fai": 0, "arc": 0}},
      "Rapier" : {"name": "Rapier", "category": "Thrusting Sword", "requires": {"str": 7, "dex": 12, "int": 0, "fai": 0, "arc": 0}},
      "Cleanrot Knight's Sword" : {"name": "Cleanrot Knight's Sword", "category": "Thrusting Sword", "requires": {"str": 13, "dex": 11, "int": 0, "fai": 0, "arc": 0}},
      "Rogier's Rapier" : {"name": "Rogier's Rapier", "category": "Thrusting Sword", "requires": {"str": 8, "dex": 17, "int": 0, "fai": 0, "arc": 0}},
      "Antspur Rapier" : {"name": "Antspur Rapier", "category": "Thrusting Sword", "requires": {"str": 10, "dex": 20, "int": 0, "fai": 0, "arc": 0}},
      "Frozen Needle" : {"name": "Frozen Needle", "category": "Thrusting Sword", "requires": {"str": 11, "dex": 18, "int": 0, "fai": 0, "arc": 0}},
      "Torch" : {"name": "Torch", "category": "Torch", "requires": {"str": 5, "dex": 5, "int": 0, "fai": 0, "arc": 0}},
      "Noble's Estoc" : {"name": "Noble's Estoc", "category": "Thrusting Sword", "requires": {"str": 9, "dex": 10, "int": 0, "fai": 0, "arc": 0}},
      "Steel-wire Torch" : {"name": "Steel-wire Torch", "category": "Torch", "requires": {"str": 10, "dex": 8, "int": 0, "fai": 0, "arc": 0}},
      "St. Trina's Torch" : {"name": "St. Trina's Torch", "category": "Torch", "requires": {"str": 10, "dex": 10, "int": 0, "fai": 14, "arc": 0}},
      "Ghostflame Torch" : {"name": "Ghostflame Torch", "category": "Torch", "requires": {"str": 10, "dex": 10, "int": 14, "fai": 0, "arc": 0}},
      "Beast-repellent Torch" : {"name": "Beast-repellent Torch", "category": "Torch", "requires": {"str": 12, "dex": 8, "int": 0, "fai": 0, "arc": 0}},
      "Sentry's Torch" : {"name": "Sentry's Torch", "category": "Torch", "requires": {"str": 15, "dex": 8, "int": 0, "fai": 15, "arc": 0}},
      "Godskin Peeler" : {"name": "Godskin Peeler", "category": "Twinblade", "requires": {"str": 17, "dex": 22, "int": 0, "fai": 0, "arc": 0}},
      "Twinned Knight Swords" : {"name": "Twinned Knight Swords", "category": "Twinblade", "requires": {"str": 16, "dex": 18, "int": 0, "fai": 0, "arc": 0}},
      "Eleonora's Poleblade" : {"name": "Eleonora's Poleblade", "category": "Twinblade", "requires": {"str": 12, "dex": 21, "int": 0, "fai": 0, "arc": 19}},
      "Gargoyle's Twinblade" : {"name": "Gargoyle's Twinblade", "category": "Twinblade", "requires": {"str": 18, "dex": 15, "int": 0, "fai": 0, "arc": 0}},
      "Gargoyle's Black Blades" : {"name": "Gargoyle's Black Blades", "category": "Twinblade", "requires": {"str": 18, "dex": 15, "int": 0, "fai": 22, "arc": 0}},
      "Large Club" : {"name": "Large Club", "category": "Warhammer", "requires": {"str": 22, "dex": 0, "int": 0, "fai": 0, "arc": 0}},
      "Greathorn Hammer" : {"name": "Greathorn Hammer", "category": "Warhammer", "requires": {"str": 22, "dex": 10, "int": 0, "fai": 0, "arc": 0}},
      "Battle Hammer" : {"name": "Battle Hammer", "category": "Warhammer", "requires": {"str": 26, "dex": 8, "int": 0, "fai": 0, "arc": 0}},
      "Great Mace" : {"name": "Great Mace", "category": "Warhammer", "requires": {"str": 28, "dex": 0, "int": 0, "fai": 0, "arc": 0}},
      "Curved Great Club" : {"name": "Curved Great Club", "category": "Warhammer", "requires": {"str": 24, "dex": 10, "int": 0, "fai": 0, "arc": 0}},
      "Celebrant's Skull" : {"name": "Celebrant's Skull", "category": "Warhammer", "requires": {"str": 18, "dex": 12, "int": 0, "fai": 0, "arc": 0}},
      "Beastclaw Greathammer" : {"name": "Beastclaw Greathammer", "category": "Warhammer", "requires": {"str": 20, "dex": 10, "int": 0, "fai": 18, "arc": 0}},
      "Twinblade" : {"name": "Twinblade", "category": "Twinblade", "requires": {"str": 10, "dex": 18, "int": 0, "fai": 0, "arc": 0}},
      "Envoy's Long Horn" : {"name": "Envoy's Long Horn", "category": "Warhammer", "requires": {"str": 23, "dex": 11, "int": 0, "fai": 18, "arc": 0}},
      "Pickaxe" : {"name": "Pickaxe", "category": "Warhammer", "requires": {"str": 22, "dex": 10, "int": 0, "fai": 0, "arc": 0}},
      "Cranial Vessel Candlestand" : {"name": "Cranial Vessel Candlestand", "category": "Warhammer", "requires": {"str": 26, "dex": 8, "int": 0, "fai": 22, "arc": 0}},
      "Great Stars" : {"name": "Great Stars", "category": "Warhammer", "requires": {"str": 22, "dex": 12, "int": 0, "fai": 0, "arc": 0}},
      "Devourer's Scepter" : {"name": "Devourer's Scepter", "category": "Warhammer", "requires": {"str": 24, "dex": 20, "int": 0, "fai": 25, "arc": 0}},
      "Brick Hammer" : {"name": "Brick Hammer", "category": "Warhammer", "requires": {"str": 31, "dex": 0, "int": 0, "fai": 0, "arc": 0}},
      "Whip" : {"name": "Whip", "category": "Whip", "requires": {"str": 8, "dex": 14, "int": 0, "fai": 0, "arc": 0}},
      "Rotten Battle Hammer" : {"name": "Rotten Battle Hammer", "category": "Warhammer", "requires": {"str": 26, "dex": 8, "int": 0, "fai": 0, "arc": 0}},
      "Thorned Whip" : {"name": "Thorned Whip", "category": "Whip", "requires": {"str": 8, "dex": 16, "int": 0, "fai": 0, "arc": 0}},
      "Magma Whip Candlestick" : {"name": "Magma Whip Candlestick", "category": "Whip", "requires": {"str": 8, "dex": 16, "int": 0, "fai": 18, "arc": 0}},
      "Hoslow's Petal Whip" : {"name": "Hoslow's Petal Whip", "category": "Whip", "requires": {"str": 10, "dex": 20, "int": 0, "fai": 0, "arc": 0}},
      "Giant's Red Braid" : {"name": "Giant's Red Braid", "category": "Whip", "requires": {"str": 18, "dex": 12, "int": 0, "fai": 21, "arc": 0}},
      "Urumi" : {"name": "Urumi", "category": "Whip", "requires": {"str": 10, "dex": 19, "int": 0, "fai": 0, "arc": 0}},
      "Buckler" : {"name": "Buckler", "category": "Small Shield", "requires": {"str": 8, "dex": 13, "int": 0, "fai": 0, "arc": 0}},
      "Perfumer's Shield" : {"name": "Perfumer's Shield", "category": "Small Shield", "requires": {"str": 8, "dex": 0, "int": 0, "fai": 0, "arc": 0}},
      "Man-serpent's Shield" : {"name": "Man-serpent's Shield", "category": "Small Shield", "requires": {"str": 8, "dex": 0, "int": 0, "fai": 0, "arc": 0}},
      "Pillory Shield" : {"name": "Pillory Shield", "category": "Small Shield", "requires": {"str": 10, "dex": 0, "int": 0, "fai": 0, "arc": 0}},
      "Rickety Shield" : {"name": "Rickety Shield", "category": "Small Shield", "requires": {"str": 8, "dex": 0, "int": 0, "fai": 0, "arc": 0}},
      "Beastman's Jar-shield" : {"name": "Beastman's Jar-shield", "category": "Small Shield", "requires": {"str": 10, "dex": 0, "int": 0, "fai": 0, "arc": 0}},
      "Red Thorn Roundshield" : {"name": "Red Thorn Roundshield", "category": "Small Shield", "requires": {"str": 8, "dex": 0, "int": 0, "fai": 0, "arc": 0}},
      "Riveted Wooden Shield" : {"name": "Riveted Wooden Shield", "category": "Small Shield", "requires": {"str": 8, "dex": 0, "int": 0, "fai": 0, "arc": 0}},
      "Scripture Wooden Shield" : {"name": "Scripture Wooden Shield", "category": "Small Shield", "requires": {"str": 8, "dex": 0, "int": 0, "fai": 0, "arc": 0}},
      "Blue-white Wooden Shield" : {"name": "Blue-white Wooden Shield", "category": "Small Shield", "requires": {"str": 8, "dex": 0, "int": 0, "fai": 0, "arc": 0}},
      "Rift Shield" : {"name": "Rift Shield", "category": "Small Shield", "requires": {"str": 8, "dex": 0, "int": 0, "fai": 0, "arc": 0}},
      "Iron Roundshield" : {"name": "Iron Roundshield", "category": "Small Shield", "requires": {"str": 8, "dex": 0, "int": 0, "fai": 0, "arc": 0}},
      "Smoldering Shield" : {"name": "Smoldering Shield", "category": "Small Shields", "requires": {"str": 10, "dex": 9, "int": 0, "fai": 0, "arc": 0}},
      "Gilded Iron Shield" : {"name": "Gilded Iron Shield", "category": "Small Shield", "requires": {"str": 8, "dex": 0, "int": 0, "fai": 0, "arc": 0}},
      "Ice Crest Shield" : {"name": "Ice Crest Shield", "category": "Small Shield", "requires": {"str": 9, "dex": 0, "int": 0, "fai": 0, "arc": 0}},
      "Spiralhorn Shield" : {"name": "Spiralhorn Shield", "category": "Small Shield", "requires": {"str": 8, "dex": 10, "int": 0, "fai": 0, "arc": 0}},
      "Marred Leather Shield" : {"name": "Marred Leather Shield", "category": "Medium Shield", "requires": {"str": 8, "dex": 0, "int": 0, "fai": 0, "arc": 0}},
      "Marred Wooden Shield" : {"name": "Marred Wooden Shield", "category": "Medium Shield", "requires": {"str": 8, "dex": 0, "int": 0, "fai": 0, "arc": 0}},
      "Coil Shield" : {"name": "Coil Shield", "category": "Small Shield", "requires": {"str": 10, "dex": 10, "int": 0, "fai": 0, "arc": 0}},
      "Kite Shield" : {"name": "Kite Shield", "category": "Medium Shield", "requires": {"str": 12, "dex": 0, "int": 0, "fai": 0, "arc": 0}},
      "Banished Knight's Shield" : {"name": "Banished Knight's Shield", "category": "Medium Shield", "requires": {"str": 14, "dex": 0, "int": 0, "fai": 0, "arc": 0}},
      "Albinauric Shield" : {"name": "Albinauric Shield", "category": "Medium Shield", "requires": {"str": 11, "dex": 0, "int": 0, "fai": 0, "arc": 0}},
      "Sun Realm Shield" : {"name": "Sun Realm Shield", "category": "Medium Shield", "requires": {"str": 8, "dex": 0, "int": 0, "fai": 0, "arc": 0}},
      "Silver Mirrorshield" : {"name": "Silver Mirrorshield", "category": "Medium Shield", "requires": {"str": 12, "dex": 10, "int": 10, "fai": 0, "arc": 0}},
      "Round Shield" : {"name": "Round Shield", "category": "Medium Shield", "requires": {"str": 8, "dex": 0, "int": 0, "fai": 0, "arc": 0}},
      "Scorpion Kite Shield" : {"name": "Scorpion Kite Shield", "category": "Medium Shield", "requires": {"str": 11, "dex": 0, "int": 0, "fai": 0, "arc": 0}},
      "Twinbird Kite Shield" : {"name": "Twinbird Kite Shield", "category": "Medium Shield", "requires": {"str": 12, "dex": 0, "int": 0, "fai": 0, "arc": 0}},
      "Blue-gold Kite Shield" : {"name": "Blue-gold Kite Shield", "category": "Medium Shield", "requires": {"str": 12, "dex": 0, "int": 0, "fai": 0, "arc": 0}},
      "Brass Shield" : {"name": "Brass Shield", "category": "Medium Shield", "requires": {"str": 16, "dex": 0, "int": 0, "fai": 0, "arc": 0}},
      "Shield Of The Guilty" : {"name": "Shield Of The Guilty", "category": "Small Shield", "requires": {"str": 8, "dex": 0, "int": 0, "fai": 0, "arc": 0}},
      "Great Turtle Shell" : {"name": "Great Turtle Shell", "category": "Medium Shield", "requires": {"str": 14, "dex": 0, "int": 0, "fai": 0, "arc": 0}},
      "Carian Knight's Shield" : {"name": "Carian Knight's Shield", "category": "Medium Shield", "requires": {"str": 10, "dex": 10, "int": 15, "fai": 0, "arc": 0}},
      "Horse Crest Wooden Shield" : {"name": "Horse Crest Wooden Shield", "category": "Medium Shield", "requires": {"str": 8, "dex": 0, "int": 0, "fai": 0, "arc": 0}},
      "Candletree Wooden Shield" : {"name": "Candletree Wooden Shield", "category": "Medium Shield", "requires": {"str": 8, "dex": 0, "int": 0, "fai": 0, "arc": 0}},
      "Large Leather Shield" : {"name": "Large Leather Shield", "category": "Medium Shield", "requires": {"str": 8, "dex": 0, "int": 0, "fai": 0, "arc": 0}},
      "Flame Crest Wooden Shield" : {"name": "Flame Crest Wooden Shield", "category": "Medium Shield", "requires": {"str": 8, "dex": 0, "int": 0, "fai": 0, "arc": 0}},
      "Hawk Crest Wooden Shield" : {"name": "Hawk Crest Wooden Shield", "category": "Medium Shield", "requires": {"str": 8, "dex": 0, "int": 0, "fai": 0, "arc": 0}},
      "Beast Crest Heater Shield" : {"name": "Beast Crest Heater Shield", "category": "Medium Shield", "requires": {"str": 10, "dex": 0, "int": 0, "fai": 0, "arc": 0}},
      "Red Crest Heater Shield" : {"name": "Red Crest Heater Shield", "category": "Medium Shield", "requires": {"str": 10, "dex": 0, "int": 0, "fai": 0, "arc": 0}},
      "Blue Crest Heater Shield" : {"name": "Blue Crest Heater Shield", "category": "Medium Shield", "requires": {"str": 10, "dex": 0, "int": 0, "fai": 0, "arc": 0}},
      "Inverted Hawk Heater Shield" : {"name": "Inverted Hawk Heater Shield", "category": "Medium Shield", "requires": {"str": 10, "dex": 0, "int": 0, "fai": 0, "arc": 0}},
      "Heater Shield" : {"name": "Heater Shield", "category": "Medium Shield", "requires": {"str": 10, "dex": 0, "int": 0, "fai": 0, "arc": 0}},
      "Black Leather Shield" : {"name": "Black Leather Shield", "category": "Medium Shield", "requires": {"str": 10, "dex": 0, "int": 0, "fai": 0, "arc": 0}},
      "Dragon Towershield" : {"name": "Dragon Towershield", "category": "Greatshield", "requires": {"str": 30, "dex": 0, "int": 0, "fai": 0, "arc": 0}},
      "Crucible Hornshield" : {"name": "Crucible Hornshield", "category": "Greatshield", "requires": {"str": 26, "dex": 0, "int": 0, "fai": 0, "arc": 0}},
      "Distinguished Greatshield" : {"name": "Distinguished Greatshield", "category": "Greatshield", "requires": {"str": 32, "dex": 0, "int": 0, "fai": 0, "arc": 0}},
      "Dragonclaw Shield" : {"name": "Dragonclaw Shield", "category": "Greatshield", "requires": {"str": 28, "dex": 12, "int": 0, "fai": 0, "arc": 0}},
      "Golden Beast Crest Shield" : {"name": "Golden Beast Crest Shield", "category": "Greatshield", "requires": {"str": 24, "dex": 0, "int": 0, "fai": 0, "arc": 0}},
      "Erdtree Greatshield" : {"name": "Erdtree Greatshield", "category": "Greatshield", "requires": {"str": 30, "dex": 0, "int": 0, "fai": 12, "arc": 0}},
      "Briar Greatshield" : {"name": "Briar Greatshield", "category": "Greatshield", "requires": {"str": 21, "dex": 0, "int": 0, "fai": 0, "arc": 0}},
      "Jellyfish Shield" : {"name": "Jellyfish Shield", "category": "Greatshield", "requires": {"str": 20, "dex": 14, "int": 0, "fai": 0, "arc": 0}},
      "Fingerprint Stone Shield" : {"name": "Fingerprint Stone Shield", "category": "Greatshield", "requires": {"str": 48, "dex": 0, "int": 0, "fai": 0, "arc": 0}},
      "Icon Shield" : {"name": "Icon Shield", "category": "Greatshield", "requires": {"str": 22, "dex": 0, "int": 0, "fai": 0, "arc": 0}},
      "Visage Shield" : {"name": "Visage Shield", "category": "Greatshield", "requires": {"str": 44, "dex": 0, "int": 0, "fai": 0, "arc": 0}},
      "One-eyed Shield" : {"name": "One-eyed Shield", "category": "Greatshield", "requires": {"str": 36, "dex": 0, "int": 0, "fai": 0, "arc": 0}},
      "Spiked Palisade Shield" : {"name": "Spiked Palisade Shield", "category": "Greatshield", "requires": {"str": 20, "dex": 0, "int": 0, "fai": 0, "arc": 0}},
      "Manor Towershield" : {"name": "Manor Towershield", "category": "Greatshield", "requires": {"str": 30, "dex": 0, "int": 0, "fai": 0, "arc": 0}},
      "Crossed-tree Towershield" : {"name": "Crossed-tree Towershield", "category": "Greatshield", "requires": {"str": 30, "dex": 0, "int": 0, "fai": 0, "arc": 0}},
      "Redmane Greatshield" : {"name": "Redmane Greatshield", "category": "Greatshield", "requires": {"str": 30, "dex": 0, "int": 0, "fai": 0, "arc": 0}},
      "Ant's Skull Plate" : {"name": "Ant's Skull Plate", "category": "Greatshield", "requires": {"str": 28, "dex": 0, "int": 0, "fai": 0, "arc": 0}},
      "Inverted Hawk Towershield" : {"name": "Inverted Hawk Towershield", "category": "Greatshield", "requires": {"str": 30, "dex": 0, "int": 0, "fai": 0, "arc": 0}},
      "Cuckoo Greatshield" : {"name": "Cuckoo Greatshield", "category": "", "requires": {"str": 32, "dex": 0, "int": 0, "fai": 0, "arc": 0}},
      "Gilded Greatshield" : {"name": "Gilded Greatshield", "category": "Greatshield", "requires": {"str": 36, "dex": 0, "int": 0, "fai": 0, "arc": 0}},
      "Golden Greatshield" : {"name": "Golden Greatshield", "category": "Greatshield", "requires": {"str": 34, "dex": 0, "int": 0, "fai": 0, "arc": 0}},
      "Haligtree Crest Greatshield" : {"name": "Haligtree Crest Greatshield", "category": "Greatshield", "requires": {"str": 36, "dex": 0, "int": 0, "fai": 0, "arc": 0}},
      "Wooden Greatshield" : {"name": "Wooden Greatshield", "category": "Greatshield", "requires": {"str": 14, "dex": 0, "int": 0, "fai": 0, "arc": 0}},
      "Lordsworn's Shield" : {"name": "Lordsworn's Shield", "category": "Greatshield", "requires": {"str": 16, "dex": 0, "int": 0, "fai": 0, "arc": 0}},
      "Briars Of Punishment" : {"name": "Briars Of Punishment", "category": "Sorcery", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 21, "arc": 0}},
      "Ancient Death Rancor" : {"name": "Ancient Death Rancor", "category": "Sorcery", "requires": {"str": 0, "dex": 0, "int": 34, "fai": 24, "arc": 0}},
      "Briars Of Sin" : {"name": "Briars Of Sin", "category": "Sorcery", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 24, "arc": 0}},
      "Cannon Of Haima" : {"name": "Cannon Of Haima", "category": "Sorcery", "requires": {"str": 0, "dex": 0, "int": 25, "fai": 0, "arc": 0}},
      "Ambush Shard" : {"name": "Ambush Shard", "category": "Sorcery", "requires": {"str": 0, "dex": 0, "int": 23, "fai": 0, "arc": 0}},
      "Carian Phalanx" : {"name": "Carian Phalanx", "category": "Sorcery", "requires": {"str": 0, "dex": 0, "int": 34, "fai": 0, "arc": 0}},
      "Adula's Moonblade" : {"name": "Adula's Moonblade", "category": "Sorcery", "requires": {"str": 0, "dex": 0, "int": 32, "fai": 0, "arc": 0}},
      "Carian Greatsword" : {"name": "Carian Greatsword", "category": "Sorcery", "requires": {"str": 0, "dex": 0, "int": 24, "fai": 0, "arc": 0}},
      "Carian Piercer" : {"name": "Carian Piercer", "category": "Sorcery", "requires": {"str": 0, "dex": 0, "int": 27, "fai": 0, "arc": 0}},
      "Carian Retaliation" : {"name": "Carian Retaliation", "category": "Sorcery", "requires": {"str": 0, "dex": 0, "int": 17, "fai": 0, "arc": 0}},
      "Carian Slicer" : {"name": "Carian Slicer", "category": "Sorcery", "requires": {"str": 0, "dex": 0, "int": 14, "fai": 0, "arc": 0}},
      "Crystal Barrage" : {"name": "Crystal Barrage", "category": "Sorcery", "requires": {"str": 0, "dex": 0, "int": 23, "fai": 0, "arc": 0}},
      "Collapsing Stars" : {"name": "Collapsing Stars", "category": "Sorcery", "requires": {"str": 0, "dex": 0, "int": 36, "fai": 0, "arc": 0}},
      "Comet Azur" : {"name": "Comet Azur", "category": "Sorcery", "requires": {"str": 0, "dex": 0, "int": 60, "fai": 0, "arc": 0}},
      "Crystal Burst" : {"name": "Crystal Burst", "category": "Sorcery", "requires": {"str": 0, "dex": 0, "int": 18, "fai": 0, "arc": 0}},
      "Comet" : {"name": "Comet", "category": "Sorcery", "requires": {"str": 0, "dex": 0, "int": 52, "fai": 0, "arc": 0}},
      "Crystal Torrent" : {"name": "Crystal Torrent", "category": "Sorcery", "requires": {"str": 0, "dex": 0, "int": 47, "fai": 0, "arc": 0}},
      "Crystal Release" : {"name": "Crystal Release", "category": "Sorcery", "requires": {"str": 0, "dex": 0, "int": 41, "fai": 0, "arc": 0}},
      "Fia's Mist" : {"name": "Fia's Mist", "category": "Sorcery", "requires": {"str": 0, "dex": 0, "int": 23, "fai": 18, "arc": 0}},
      "Eternal Darkness" : {"name": "Eternal Darkness", "category": "Sorcery", "requires": {"str": 0, "dex": 0, "int": 35, "fai": 0, "arc": 0}},
      "Frozen Armament" : {"name": "Frozen Armament", "category": "Sorcery", "requires": {"str": 0, "dex": 0, "int": 15, "fai": 0, "arc": 0}},
      "Founding Rain Of Stars" : {"name": "Founding Rain Of Stars", "category": "Sorcery", "requires": {"str": 0, "dex": 0, "int": 52, "fai": 0, "arc": 0}},
      "Explosive Ghostflame" : {"name": "Explosive Ghostflame", "category": "Sorcery", "requires": {"str": 0, "dex": 0, "int": 42, "fai": 30, "arc": 0}},
      "Freezing Mist" : {"name": "Freezing Mist", "category": "Sorcery", "requires": {"str": 0, "dex": 0, "int": 21, "fai": 0, "arc": 0}},
      "Gelmir's Fury" : {"name": "Gelmir's Fury", "category": "Sorcery", "requires": {"str": 0, "dex": 0, "int": 28, "fai": 15, "arc": 0}},
      "Gavel Of Haima" : {"name": "Gavel Of Haima", "category": "Sorcery", "requires": {"str": 0, "dex": 0, "int": 25, "fai": 0, "arc": 0}},
      "Glintstone Arc" : {"name": "Glintstone Arc", "category": "Sorcery", "requires": {"str": 0, "dex": 0, "int": 13, "fai": 0, "arc": 0}},
      "Glintstone Cometshard" : {"name": "Glintstone Cometshard", "category": "Sorcery", "requires": {"str": 0, "dex": 0, "int": 36, "fai": 0, "arc": 0}},
      "Glintstone Pebble" : {"name": "Glintstone Pebble", "category": "Sorcery", "requires": {"str": 0, "dex": 0, "int": 10, "fai": 0, "arc": 0}},
      "Glintstone Stars" : {"name": "Glintstone Stars", "category": "Sorcery", "requires": {"str": 0, "dex": 0, "int": 12, "fai": 0, "arc": 0}},
      "Glintstone Icecrag" : {"name": "Glintstone Icecrag", "category": "Sorcery", "requires": {"str": 0, "dex": 0, "int": 15, "fai": 0, "arc": 0}},
      "Glintblade Phalanx" : {"name": "Glintblade Phalanx", "category": "Sorcery", "requires": {"str": 0, "dex": 0, "int": 22, "fai": 0, "arc": 0}},
      "Gravity Well" : {"name": "Gravity Well", "category": "Sorcery", "requires": {"str": 0, "dex": 0, "int": 17, "fai": 0, "arc": 0}},
      "Great Glintstone Shard" : {"name": "Great Glintstone Shard", "category": "Sorcery", "requires": {"str": 0, "dex": 0, "int": 16, "fai": 0, "arc": 0}},
      "Lucidity" : {"name": "Lucidity", "category": "Sorcery", "requires": {"str": 0, "dex": 0, "int": 17, "fai": 0, "arc": 0}},
      "Greatblade Phalanx" : {"name": "Greatblade Phalanx", "category": "Sorcery", "requires": {"str": 0, "dex": 0, "int": 29, "fai": 0, "arc": 0}},
      "Great Oracular Bubble" : {"name": "Great Oracular Bubble", "category": "Sorcery", "requires": {"str": 0, "dex": 0, "int": 25, "fai": 0, "arc": 18}},
      "Oracle Bubble" : {"name": "Oracle Bubble", "category": "Sorcery", "requires": {"str": 0, "dex": 0, "int": 10, "fai": 0, "arc": 0}},
      "Loretta's Greatbow" : {"name": "Loretta's Greatbow", "category": "Sorcery", "requires": {"str": 0, "dex": 0, "int": 26, "fai": 0, "arc": 0}},
      "Loretta's Mastery" : {"name": "Loretta's Mastery", "category": "Sorcery", "requires": {"str": 0, "dex": 0, "int": 46, "fai": 0, "arc": 0}},
      "Magic Downpour" : {"name": "Magic Downpour", "category": "Sorcery", "requires": {"str": 0, "dex": 0, "int": 15, "fai": 0, "arc": 0}},
      "Magic Glintblade" : {"name": "Magic Glintblade", "category": "Sorcery", "requires": {"str": 0, "dex": 0, "int": 14, "fai": 0, "arc": 0}},
      "Magma Shot" : {"name": "Magma Shot", "category": "Sorcery", "requires": {"str": 0, "dex": 0, "int": 19, "fai": 10, "arc": 0}},
      "Meteorite" : {"name": "Meteorite", "category": "Sorcery", "requires": {"str": 0, "dex": 0, "int": 30, "fai": 0, "arc": 0}},
      "Night Comet" : {"name": "Night Comet", "category": "Sorcery", "requires": {"str": 0, "dex": 0, "int": 38, "fai": 0, "arc": 0}},
      "Meteorite Of Astel" : {"name": "Meteorite Of Astel", "category": "Sorcery", "requires": {"str": 0, "dex": 0, "int": 55, "fai": 0, "arc": 0}},
      "Night Shard" : {"name": "Night Shard", "category": "Sorcery", "requires": {"str": 0, "dex": 0, "int": 18, "fai": 0, "arc": 0}},
      "Night Maiden's Mist" : {"name": "Night Maiden's Mist", "category": "Sorcery", "requires": {"str": 0, "dex": 0, "int": 14, "fai": 0, "arc": 0}},
      "Rancorcall" : {"name": "Rancorcall", "category": "Sorcery", "requires": {"str": 0, "dex": 0, "int": 16, "fai": 14, "arc": 0}},
      "Oracle Bubbles" : {"name": "Oracle Bubbles", "category": "Sorcery", "requires": {"str": 0, "dex": 0, "int": 19, "fai": 0, "arc": 15}},
      "Rennala's Full Moon" : {"name": "Rennala's Full Moon", "category": "Sorcery", "requires": {"str": 0, "dex": 0, "int": 70, "fai": 0, "arc": 0}},
      "Ranni's Dark Moon" : {"name": "Ranni's Dark Moon", "category": "Sorcery", "requires": {"str": 0, "dex": 0, "int": 68, "fai": 0, "arc": 0}},
      "Rock Blaster" : {"name": "Rock Blaster", "category": "Sorcery", "requires": {"str": 0, "dex": 0, "int": 21, "fai": 0, "arc": 0}},
      "Roiling Magma" : {"name": "Roiling Magma", "category": "Sorcery", "requires": {"str": 0, "dex": 0, "int": 21, "fai": 12, "arc": 0}},
      "Rykard's Rancor" : {"name": "Rykard's Rancor", "category": "Sorcery", "requires": {"str": 0, "dex": 0, "int": 40, "fai": 18, "arc": 0}},
      "Rock Sling" : {"name": "Rock Sling", "category": "Sorcery", "requires": {"str": 0, "dex": 0, "int": 18, "fai": 0, "arc": 0}},
      "Scholar's Armament" : {"name": "Scholar's Armament", "category": "Sorcery", "requires": {"str": 0, "dex": 0, "int": 12, "fai": 0, "arc": 0}},
      "Scholar's Shield" : {"name": "Scholar's Shield", "category": "Sorcery", "requires": {"str": 0, "dex": 0, "int": 12, "fai": 0, "arc": 0}},
      "Shard Spiral" : {"name": "Shard Spiral", "category": "Sorcery", "requires": {"str": 0, "dex": 0, "int": 27, "fai": 0, "arc": 0}},
      "Shatter Earth" : {"name": "Shatter Earth", "category": "Sorcery", "requires": {"str": 0, "dex": 0, "int": 15, "fai": 0, "arc": 0}},
      "Starlight" : {"name": "Starlight", "category": "Sorcery", "requires": {"str": 0, "dex": 0, "int": 15, "fai": 0, "arc": 0}},
      "Star Shower" : {"name": "Star Shower", "category": "Sorcery", "requires": {"str": 0, "dex": 0, "int": 24, "fai": 0, "arc": 0}},
      "Stars Of Ruin" : {"name": "Stars Of Ruin", "category": "Sorcery", "requires": {"str": 0, "dex": 0, "int": 43, "fai": 0, "arc": 0}},
      "Shattering Crystal" : {"name": "Shattering Crystal", "category": "Sorcery", "requires": {"str": 0, "dex": 0, "int": 38, "fai": 0, "arc": 0}},
      "Swift Glintstone Shard" : {"name": "Swift Glintstone Shard", "category": "Sorcery", "requires": {"str": 0, "dex": 0, "int": 12, "fai": 0, "arc": 0}},
      "Terra Magicus" : {"name": "Terra Magicus", "category": "Sorcery", "requires": {"str": 0, "dex": 0, "int": 20, "fai": 0, "arc": 0}},
      "Unseen Blade" : {"name": "Unseen Blade", "category": "Sorcery", "requires": {"str": 0, "dex": 0, "int": 12, "fai": 0, "arc": 0}},
      "Unseen Form" : {"name": "Unseen Form", "category": "Sorcery", "requires": {"str": 0, "dex": 0, "int": 16, "fai": 0, "arc": 0}},
      "Thops's Barrier" : {"name": "Thops's Barrier", "category": "Sorcery", "requires": {"str": 0, "dex": 0, "int": 18, "fai": 0, "arc": 0}},
      "Zamor Ice Storm" : {"name": "Zamor Ice Storm", "category": "Sorcery", "requires": {"str": 0, "dex": 0, "int": 36, "fai": 0, "arc": 0}},
      "Tibia's Summons" : {"name": "Tibia's Summons", "category": "Sorcery", "requires": {"str": 0, "dex": 0, "int": 28, "fai": 20, "arc": 0}},
      "Ancient Dragons' Lightning Strike" : {"name": "Ancient Dragons' Lightning Strike", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 26, "arc": 0}},
      "Aspects Of The Crucible: Horns" : {"name": "Aspects Of The Crucible: Horns", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 27, "arc": 0}},
      "Agheel's Flame" : {"name": "Agheel's Flame", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 23, "arc": 15}},
      "Aspects Of The Crucible: Tail" : {"name": "Aspects Of The Crucible: Tail", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 27, "arc": 0}},
      "Barrier Of Gold" : {"name": "Barrier Of Gold", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 24, "arc": 0}},
      "Ancient Dragons' Lightning Spear" : {"name": "Ancient Dragons' Lightning Spear", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 0, "arc": 0}},
      "Beast Claw" : {"name": "Beast Claw", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 8, "arc": 0}},
      "Aspect Of The Crucible: Breath" : {"name": "Aspect Of The Crucible: Breath", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 27, "arc": 0}},
      "Bestial Constitution" : {"name": "Bestial Constitution", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 9, "arc": 0}},
      "Bestial Sling" : {"name": "Bestial Sling", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 10, "arc": 0}},
      "Black Blade" : {"name": "Black Blade", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 46, "arc": 0}},
      "Black Flame Ritual" : {"name": "Black Flame Ritual", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 42, "arc": 0}},
      "Black Flame" : {"name": "Black Flame", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 20, "arc": 0}},
      "Black Flame Blade" : {"name": "Black Flame Blade", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 17, "arc": 0}},
      "Bestial Vitality" : {"name": "Bestial Vitality", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 12, "arc": 0}},
      "Black Flame's Protection" : {"name": "Black Flame's Protection", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 30, "arc": 0}},
      "Blessing's Boon" : {"name": "Blessing's Boon", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 24, "arc": 0}},
      "Blessing Of The Erdtree" : {"name": "Blessing Of The Erdtree", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 38, "arc": 0}},
      "Bloodflame Blade" : {"name": "Bloodflame Blade", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 12, "arc": 10}},
      "Bloodflame Talons" : {"name": "Bloodflame Talons", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 13, "arc": 15}},
      "Bloodboon" : {"name": "Bloodboon", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 14, "arc": 17}},
      "Borealis's Mist" : {"name": "Borealis's Mist", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 23, "arc": 15}},
      "Cure Poison" : {"name": "Cure Poison", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 10, "arc": 0}},
      "Burn O Flame!" : {"name": "Burn O Flame!", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 27, "arc": 0}},
      "Darkness" : {"name": "Darkness", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 18, "arc": 0}},
      "Death Lightning" : {"name": "Death Lightning", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 47, "arc": 0}},
      "Discus Of Light" : {"name": "Discus Of Light", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 13, "fai": 13, "arc": 0}},
      "Divine Fortification" : {"name": "Divine Fortification", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 10, "arc": 0}},
      "Dragonbolt Blessing" : {"name": "Dragonbolt Blessing", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 21, "arc": 0}},
      "Dragonice" : {"name": "Dragonice", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 15, "arc": 12}},
      "Dragonclaw" : {"name": "Dragonclaw", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 17, "arc": 13}},
      "Dragonfire" : {"name": "Dragonfire", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 15, "arc": 12}},
      "Dragonmaw" : {"name": "Dragonmaw", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 24, "arc": 16}},
      "Ekzyke's Decay" : {"name": "Ekzyke's Decay", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 23, "arc": 15}},
      "Ekzykes's Decay" : {"name": "Ekzykes's Decay", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 23, "arc": 15}},
      "Fire's Deadly Sin" : {"name": "Fire's Deadly Sin", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 19, "arc": 0}},
      "Erdtree Heal" : {"name": "Erdtree Heal", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 42, "arc": 0}},
      "Flame, Fall Upon Them" : {"name": "Flame, Fall Upon Them", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 28, "arc": 0}},
      "Ezykes's Decay" : {"name": "Ezykes's Decay", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 23, "arc": 15}},
      "Electrify Armament" : {"name": "Electrify Armament", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 15, "arc": 0}},
      "Flame Fortification" : {"name": "Flame Fortification", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 10, "arc": 0}},
      "Flame Of The Fell God" : {"name": "Flame Of The Fell God", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 41, "arc": 0}},
      "Elden Stars" : {"name": "Elden Stars", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 50, "arc": 0}},
      "Flame, Protect Me" : {"name": "Flame, Protect Me", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 24, "arc": 0}},
      "Fortissax's Lightning Spear" : {"name": "Fortissax's Lightning Spear", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 46, "arc": 0}},
      "Frozen Lightning Spear" : {"name": "Frozen Lightning Spear", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 34, "arc": 0}},
      "Golden Lightning Fortification" : {"name": "Golden Lightning Fortification", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 24, "arc": 0}},
      "Frenzied Burst" : {"name": "Frenzied Burst", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 22, "arc": 0}},
      "Giantsflame Take Thee" : {"name": "Giantsflame Take Thee", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 30, "arc": 0}},
      "Golden Vow (spell)" : {"name": "Golden Vow (spell)", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 25, "arc": 0}},
      "Gurrang's Beast Claw" : {"name": "Gurrang's Beast Claw", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 15, "arc": 0}},
      "Immutable Shield" : {"name": "Immutable Shield", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 19, "fai": 19, "arc": 0}},
      "Heal" : {"name": "Heal", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 12, "arc": 0}},
      "Howl Of Shabriri" : {"name": "Howl Of Shabriri", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 33, "arc": 0}},
      "Great Heal" : {"name": "Great Heal", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 15, "arc": 0}},
      "Greyoll's Roar" : {"name": "Greyoll's Roar", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 28, "arc": 17}},
      "Inescapable Frenzy" : {"name": "Inescapable Frenzy", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 21, "arc": 0}},
      "Honed Bolt" : {"name": "Honed Bolt", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 24, "arc": 0}},
      "Lansseax's Glaive" : {"name": "Lansseax's Glaive", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 40, "arc": 0}},
      "Lightning Fortification" : {"name": "Lightning Fortification", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 10, "arc": 0}},
      "Lord's Aid" : {"name": "Lord's Aid", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 12, "arc": 0}},
      "Lightning Spear" : {"name": "Lightning Spear", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 17, "arc": 0}},
      "Law Of Causality" : {"name": "Law Of Causality", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 0, "arc": 0}},
      "Litany Of Proper Death" : {"name": "Litany Of Proper Death", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 17, "fai": 17, "arc": 0}},
      "Law Of Regression" : {"name": "Law Of Regression", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 37, "fai": 0, "arc": 0}},
      "Lightning Strike" : {"name": "Lightning Strike", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 28, "arc": 0}},
      "Lord's Divine Fortification" : {"name": "Lord's Divine Fortification", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 27, "arc": 0}},
      "Lord's Heal" : {"name": "Lord's Heal", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 20, "arc": 0}},
      "Order Healing" : {"name": "Order Healing", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 0, "arc": 0}},
      "Noble Presence" : {"name": "Noble Presence", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 26, "arc": 0}},
      "Order's Blade" : {"name": "Order's Blade", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 13, "fai": 13, "arc": 0}},
      "Magic Fortification" : {"name": "Magic Fortification", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 10, "arc": 0}},
      "O, Flame!" : {"name": "O, Flame!", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 16, "arc": 0}},
      "Magma Breath" : {"name": "Magma Breath", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 14, "arc": 10}},
      "Pest Threads" : {"name": "Pest Threads", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 11, "arc": 0}},
      "Protection Of The Erdtree" : {"name": "Protection Of The Erdtree", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 35, "arc": 0}},
      "Poison Armament" : {"name": "Poison Armament", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 10, "arc": 0}},
      "Placidusax's Ruin" : {"name": "Placidusax's Ruin", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 36, "arc": 0}},
      "Poison Mist" : {"name": "Poison Mist", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 12, "arc": 0}},
      "Radagon's Rings Of Light" : {"name": "Radagon's Rings Of Light", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 31, "fai": 31, "arc": 0}},
      "Rotten Breath" : {"name": "Rotten Breath", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 15, "arc": 12}},
      "Rejection" : {"name": "Rejection", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 12, "arc": 0}},
      "Smarag's Glintstone Breath" : {"name": "Smarag's Glintstone Breath", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 23, "arc": 15}},
      "Stone Of Gurranq" : {"name": "Stone Of Gurranq", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 13, "arc": 0}},
      "Surge, O Flame!" : {"name": "Surge, O Flame!", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 9, "arc": 0}},
      "Shadow Bait" : {"name": "Shadow Bait", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 13, "arc": 0}},
      "Scouring Black Flame" : {"name": "Scouring Black Flame", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 28, "arc": 0}},
      "Scarlet Aeonia" : {"name": "Scarlet Aeonia", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 35, "arc": 0}},
      "Swarm Of Flies" : {"name": "Swarm Of Flies", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 11, "arc": 16}},
      "The Flame Of Frenzy" : {"name": "The Flame Of Frenzy", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 16, "arc": 0}},
      "Theodorix's Magma" : {"name": "Theodorix's Magma", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 21, "arc": 14}},
      "Unendurable Frenzy" : {"name": "Unendurable Frenzy", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 31, "arc": 0}},
      "Triple Rings Of Light" : {"name": "Triple Rings Of Light", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 23, "fai": 23, "arc": 0}},
      "Whirl, O Flame!" : {"name": "Whirl, O Flame!", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 13, "arc": 0}},
      "Urgent Heal" : {"name": "Urgent Heal", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 8, "arc": 0}},
      "Wrath Of Gold" : {"name": "Wrath Of Gold", "category": "Incantation", "requires": {"str": 0, "dex": 0, "int": 0, "fai": 32, "arc": 0}},

    };
    return map;
}
function cate_list() { return ['', 'Axe', 'Ballista', 'Bow', 'Claw', 'Colossal Sword', 'Colossal Weapon', 'Crossbow', 'Curved Greatsword', 'Curved Sword', 'Dagger', 'Fist', 'Flail', 'Glintstone Staff', 'Great Spear', 'Greataxe', 'Greatbow', 'Greatshield', 'Greatsword', 'Halberd', 'Hammer', 'Heavy Thrusting Sword', 'Incantation', 'Katana', 'Light Bow', 'Medium Shield', 'Reaper', 'Sacred Seal', 'Small Shield', 'Small Shields', 'Sorcery', 'Spear', 'Straight Sword', 'Thrusting Sword', 'Torch', 'Twinblade', 'Warhammer', 'Whip'] }